org: antonioevaldo
app: escola-serverless
service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: api/index.cadastrarAlunos
    events:
      - httpApi:
          path: /admin/alunos_batch
          method: post

plugins:
  - serverless-offline
